### ISSUE TITLE
Issues when running the `basic usage` example

### ISSUE THREAD

**Issue by martinaxgloria** [Westfall-io/sysml2py#84]
Hi @chriscox-westfall, thank you for your work on this project!
I’ve noticed some issues when I tried to run the basic example I found in your main README.md

I installed `sysml2py` with:

```
python -m pip install sysml2py
```

Then, I created a new .py and I attached the example I mentioned:

```py
from sysml2py.formatting import classtree
from sysml2py import Attribute, Part

import astropy.units as u
a = Attribute()._set_name('mass')
a.set_value(100*u.kg)
b = Attribute()._set_name('thrust')
b.set_value(1000*u.N)
c = Part()._set_name("Stage_1")._set_name("'3.1'", short=True)
c._set_child(a)
c._set_child(b)
v = "Stage_1.thrust"
c._get_child(v).set_value(c._get_child(v).get_value()+199*u.N)
print(classtree(c.dump()).dump())
```

I ran the script and this is the output:

```
------------


Definition: part <'3.1'> Stage_1 {
   attribute mass= 100.0[kg];
   attribute thrust= 1199.0[N];
}
Traceback (most recent call last):
  File "/home/mgloria/iit/test/test.py", line 14, in <module>
    print(classtree(c.dump()).dump())
  File "/home/mgloria/.local/lib/python3.10/site-packages/sysml2py/formatting.py", line 47, in classtree
    return RootNamespace(model)
  File "/home/mgloria/.local/lib/python3.10/site-packages/sysml2py/grammar/classes.py", line 54, in __init__
    if valid_definition(definition, "PackageBodyElement"):
  File "/home/mgloria/.local/lib/python3.10/site-packages/sysml2py/grammar/classes.py", line 27, in valid_definition
    raise TypeError("This does not seem to be valid.")
TypeError: This does not seem to be valid.
```

It would be very nice to be able to use this tool. Thanks a lot in advance!

**Comment by chriscox-westfall** [comment]
I haven't yet decided whether I want to keep pushing this library or not, I think there are others that are further ahead. You might also try this library as they seem to have a lot more of the language covered.

https://github.com/DAF-Digital-Transformation-Office/PySysML2

**Comment by msafakkoc** [comment]
Hello, I'm having the same issue as well. I've also checked the library that you've shared but it does not enable me to define models with SysML syntax and get sysmlv2 notation, which is what i'm looking for. I'd be happy if you can help to solve the problem mentioned above.

**Comment by chriscox-westfall** [comment]
I'll take a look over the next few days to see what's going on.

**Comment by msafakkoc** [comment]
Hello Mr. Cox, is  there any update about the issue?

**Comment by chriscox-westfall** [comment]
Looks like the issue is in the classtree formatting function, but it seems unnecessary now. I'll look to fix the classtree function, but the following code should work.

```
from sysml2py import Attribute, Part

import astropy.units as u
a = Attribute()._set_name('mass')
a.set_value(100*u.kg)
b = Attribute()._set_name('thrust')
b.set_value(1000*u.N)
c = Part()._set_name("Stage_1")._set_name("'3.1'", short=True)
c._set_child(a)
c._set_child(b)
v = "Stage_1.thrust"
c._get_child(v).set_value(c._get_child(v).get_value()+199*u.N)
print(c.dump())
```
